# -*- coding: utf-8 -*-
"""forgithub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQddUTEEvQSxpXcFNSqiawCnr1bxa9Ll
"""

print("hello world")

