# -*- coding: utf-8 -*-
"""python1regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IA687ViEMGfMz569tLhnwI5jrIEpHCP-
"""

#python--version

"""founder:guido van rossum

fundamentals of python
1. interger
2. varables
3. functions
4. datatype
5. input(),print()
6. float
7. typecasting: to change value from one data type to another the cast of the thing

VARIABLES:
this is  a container to store values
a=56
b='sam'
c=78.00

(a)Global variable
--> entrirely modify
(b)Local Variable
-->specific block of code modify.

datatype;
(a) interger:...>all positive and negetive interger
ex. 23,34,,44
(b). Float---> all decimal values
ex---> 34.5

(c)string:  'single qoutes', "double_qoutrs", '''triple_quotes'''

 (D) Boolean:--> true,false
 ex: 5>4: true
"""

#typecasting
a=67
type(a)
b=float(a)
type(b)
b

#print()function:

a=1
print(a)
print("printing a")
b=2
print("printing b")
print(b)

a= int(input("enter 1st unmber:"))
b=int(input("enter2 nd nuber"))
c=a+b
c
#this is type casting

a= (input("enter 1st unmber:"))
b=(input("enter2 nd nuber"))
c=a+b
c

"""commnly used operators:
1. Add: 5+3=8
2. sub: 5-3=2
3. mul : 5*3=15
4. division: 5/3=1.6
5. floor division(//) --> round 5//3 =1
6. module(%)--> remandier cal =  25%10=5(rem)
7. equal to (=) --> assgin values a=10,b='aan'
8. eqal equal to (==)--> for comparsion
9. not equal to (!=) --> 'sam'!=10
10. grater than  5>4
11. less than   4<5
12. greater than or equalto >=
13. less than or equal to <=

conditional satement in python
1. if
2. else
3. elif
"""

#ex.1

a=input("enter ur name")
if(a=='sam'):
 print("yes")
elif(a=='rahul'):
 print("no")
elif(a=='ankit'):
 print("ok")
else:
 print("print a valid name...")

#ex2

print("we provide these items: pizza,burger,icecream,sandwich")
print("MENU: Pizza=100 , burger=50 ,icecream=50,sandwich=100")



a=input("enter your item:  ")

if(a=="pizza"):
  print("pizza is availbale")
  b=int(input("enter the number : "))
  print("total price : ", b*100)
  c=b*100
  if(c<=1000):
    print("your 10% discounted price  is : ", c-(c*0.1))
  elif(1000<c<2000):
    print("your 10% discounted price  is : ", c-(c*0.1))
  elif(c>=2000):
    print("your 20% discounted price  is : ", c-(c*0.2))
  elif(c>1000):
   print("your price  is : ", c)

#for burger
elif(a=="burger"):
 print("burger is availbale")
 b=int(input("enter the number : "))
 print("total price : ", b*50)
 c=b*50
 if(c<1000):
    print("your amount is",c)
 elif(1000<c<2000):
  print("your 10% discounted price  is : ", c-(c*0.1))
 elif(c>=2000):
  print("your 20% discounted price  is : ", c-(c*0.2))
 elif(c>=1000):
  print(" you have given 10% discount", c-(c*0.1))

#for icecream
elif(a=="icecream"):
 print("icecream  is availbale")
 b=int(input("enter the number : "))
 print("total price : ", b*50)
 c=b*50
 if(c<1000):
    print("your amount is",c)
 elif(1000<c<2000):
  print("your 10% discounted price  is : ", c-(c*0.1))
 elif(c>=2000):
  print("your 20% discounted price  is : ", c-(c*0.2))
 elif(c>=1000):
  print(" you have given 10% discount", c-(c*0.1))

#for sandwich
elif(a=="sandwich"):
 print("sandwich is availbale")
 b=int(input("enter the number : "))
 print("total price : ", b*100)
 c=b*100
 if(c<1000):
    print("your amount is",c)
 elif(1000<c<2000):
  print("your 10% discounted price  is : ", c-(c*0.1))
 elif(c>=2000):
  print("your 20% discounted price  is : ", c-(c*0.2))
 elif(c>=1000):
  print(" you have given 10% discount", c-(c*0.1))

else:
 print("invalid item")

a=100
b=100*0.1
b
c=a-b
c

#student information system
#user (pyhton , java , mernstack)
#--> fees, timeduration

print(" hello there please select your course: ")
print("1.python")
print("2.java")
print("3.mernstack")
a=(input("enter your course: "))
if(a=='python'):
 print("your have selected python , the course fee is 1000rs and the duration is 3 months")
elif(a=='java'):
 print("your have selected java , the course fee is 2000rs and the duration is 4 months")
elif(a=='mernstack'):
 print("your have selected mernstack , the course fee is 3000rs and the duration is 5 months")
else:
 print("invalid course")

#loops in python

#1. for loop
#index=0 , length=1
#starting values will include and last value will exclude

#method-1
for i in range(1,5):
  print(i)

for i in range(1,10,2):
  print(i)



"""here 2 is the gap

"""

#nested for looop

for i in range(3):
  for j in range(2):
    print(f"i={i},j={j}")

i = input("enter your name: ")
print(f"hello , {i}, thank you for reaching out")

#star pattern :

n= 5
for i in range(1,n+1):
  print("*"*i)

#hollow star pattern

n=5
for i in range (1,n+1):
  if i==1 or i==n:
   print("*" * i)#for 1st and last rows
  else:
    print("*" + " " * (i-2) + "*")#middle rows with sapces

#pyramid pattern

n=5
for i in range(1,n+1):
  print(" " * (n-i) + "*" * (2*i-1))

# n=5 ,i=1
#  " "*(5-1)+" *" * (2*1-1)

#this is the logic

#While Loop

#1. initialization
#2.condition
#3.increment or decrement

#printing 1 to 4
i=1
n=4
while i<=n : #condition
  print(i)
  i=i+1 #increment

i = int(input("enter a number: "))
n=int(input("enter last  number: "))
p= int(input("enter the gap: "))
while(i<=n):
  print(i)
  i=i+p

#reversing the numbers

i= 5
n=1
while(i>=n):
  print(i)
  i=i-1

#sum of elements
i=1
n=4
sum=0
while(i<=n):
 sum=sum+i
 i=i+1
print(sum)

print("enter your name")
name=input()
print("hello",name)

#take three variable:

a=int(input("enter 1st value"))
b=int(input("enter 2nd value "))
c=int(input(" enter 3d value"))

if (a>b and a>c):
  print("a is greater: ")
elif(b>a and b>c):
  print("b isgreater: ")
else:
  print("c is greaterr: ")

x=10                                                     #pyhton is a dynamic typed programming language
if(x>=10):                                                   #automatically detect  datatype at runtime
  print("hello")

x=8                                                    #pyhton is a dynamic typed programming language
if(x>=10):                                                   #automatically detect  datatype at runtime
  print("hello")
else:
  print("false condition")

x=12
y=20
x>10 and y>15

x=5
y=20
if(x>10 or y>15):
  print("hello")
else:
  print("false condition")

# prompt: #variable is multiple of 2 and 6 print hi otherwise bye

x=int(input("enter a number"))
if(x%2==0 ):
  print("hi")
elif(x%6==0):
  print("hello")
else:
  print("bye")

# take a varialbe name as age if
#age>10 print child
# age>18 adult
#age>30 mature
#age >60 old citizen
#else infant

age=int(input("enter your age"))
if(age<=10 and age>=18):
  print("child")
elif(age>=18):
    print("adult")
elif(age>=30):
   print("mature")
elif(age>=60):
  print("old citizen")
else:
   print("infant")

#nested if else
age=int(input("enter your age"))
if(age>=5):
  print("addhar card is printed")
  if(age>=18):                                                       #be sure of any indentation
    print(" aadhar card  + pan card can be  linked")
  else:
    print("pan card not created")
else:
  print("age is small")

#if a number is div by2 print div by 2
#if a number is div by 3 print div by 6
#other wise number is not divisibele by 2 or 3

num=int(input("enter a number"))
if(num%2==0):
  print("this number is divisible by 2")
  if(num%3==0):
    print("this number is divisible by 3")
  else:
    print("this num is divisible by 6")
else:
  print("this num is not divisibele by 2 or 3")

print("hey " , end= "- ")
print("hello")

#learning assginmetn

#diff bw py ver2 and ver3 of pyhton

#slicing opertors